### ISSUE TITLE
Character Doesn't Load after Creation

### ISSUE THREAD

**Issue by pflegera** [cse403RollBuddy/Main#9]
Component: Playpage
Version: Beta
OS: Windows 10
Browser: Chrome
Detailed Description: The character does not load into the Playpage after creation
Steps to Reproduce: Create a character, then click 'Update and Play'
Actual Results: The Playpage had options for all previously created characters, but not the newest created character
Expected Results: The new character should be an option in the drop down menu

**Comment by stevenpater** [comment]
I thought I remembered Joan saying she fixed this issue... is that true?
